# This is a basic workflow to help you get started with Actions
 
name: Flutter build 2 apk
 
# Controls when the workflow will run
on:
  workflow_dispatch:
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
 
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
 
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.10'
      - run: flutter config --no-analytics
      - run: flutter pub get
      - run: flutter build apk --flavor development
 
    
 
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: vanni-build-apk
          path: release
 
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: release.apk
          asset_name: vanni-build-apk
          tag: ${{ github.ref }}
          overwrite: true
 
 
# You may pin to the exact commit or the version.
# uses: subosito/flutter-action@4389e6cbc6cb8a4b18c628ff96ff90be0e926aa8
 
